import { ISpeechRecognition, ISpeechGrammarList } from './contracts';
export declare class SpeechRecognition implements ISpeechRecognition {
    private _apiKey?;
    private recognizer;
    apiKey: string;
    constructor(_apiKey?: string | undefined);
    start(): void;
    stop(): void;
    abort(): void;
    private handleEvent;
    private handleHypothesis;
    private handleResult;
    private recognitionStartSuccess;
    private recognitionStartFailed;
    private setupRecognizer;
    onaudiostart: (() => void) | null;
    onaudioend: (() => void) | null;
    onstart: (() => void) | null;
    onend: (() => void) | null;
    onerror: ((event: any) => void) | null;
    onnomatch: (() => void) | null;
    onresult: ((event: any) => void) | null;
    onsoundstart: (() => void) | null;
    onsoundend: (() => void) | null;
    onspeechstart: (() => void) | null;
    onspeechend: (() => void) | null;
    grammars: ISpeechGrammarList;
    lang: string;
    continuous: boolean;
    interimResults: boolean;
    maxAlternatives: number;
    serviceURI: string;
}
